-- ===============================
-- Kumo PostgreSQL Database Schema
-- ===============================

-- =========
--   ENUMS
-- =========

CREATE TYPE estado_usuario AS ENUM ('PENDIENTE_VERIFICACION', 'ACTIVO', 'BLOQUEADO', 'ELIMINACION_PROGRAMADA');
CREATE TYPE formato_fecha AS ENUM ('DD/MM/AAAA', 'MM/DD/AAAA', 'AAAA-MM-DD');
CREATE TYPE estado_exportacion AS ENUM ('PENDIENTE', 'PROCESANDO', 'COMPLETADA', 'FALLIDA');
CREATE TYPE tipo_operacion_auditoria AS ENUM ('INSERCION', 'MODIFICACION', 'ELIMINACION');
CREATE TYPE dia_semana AS ENUM ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES','SABADO', 'DOMINGO');

-- =================
--      TABLAS
-- =================

-- Módulo de Seguridad (Gestión de cuentas)

/*
 * Almacena los roles del sistema (justificada para Spring Security).
 */
CREATE TABLE roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

/*
 * Almacena todos los usuarios de Kumo (SRS 4.1 y 4.6)
 */
CREATE TABLE usuarios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    nombre VARCHAR(100),
    avatar_url TEXT,
    email VARCHAR(255) NOT NULL UNIQUE,
    clave_hash VARCHAR(255) NOT NULL,
    estado estado_usuario NOT NULL DEFAULT 'PENDIENTE_VERIFICACION',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ
);

CREATE INDEX idx_usuarios_email ON usuarios(email);

/*
 * Tabla pivote para la relación N:M entre usuarios y roles.
 */
CREATE TABLE usuario_roles (
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,

    PRIMARY KEY (usuario_id, rol_id)
);

/*
 * Almacena las preferencias de visualización del usuario (RF-PER-PREF-001, RF-PER-PREF-002)
 * Es una relación 1:1 con la tabla 'usuarios' para cumplir SRP.
 */
CREATE TABLE preferencias_usuario (
    usuario_id BIGINT PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,    
    zona_horaria VARCHAR(100) NOT NULL DEFAULT 'America/Lima',
    formato_fecha formato_fecha NOT NULL DEFAULT 'DD/MM/AAAA'
);

/*
 * Registra los intentos de inicio de sesión fallidos (RF-AUT-INI-003).
 */
CREATE TABLE intentos_login (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    email VARCHAR(255) NOT NULL,
    ip_direccion VARCHAR(50),
    fecha_intento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_intentos_login_email ON intentos_login(email);

/*
 * Almacena los tokens para restablecer contraseña (RF-AUT-PAS-001).
 */
CREATE TABLE tokens_recuperacion_clave (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,    
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    utilizado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_tokens_recuperacion_hash ON tokens_recuperacion_clave(token_hash);

/*
 * Registra las solicitudes de exportación de datos (RF-POR-EXP-001).
 */
CREATE TABLE solicitudes_exportacion (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,    
    estado estado_exportacion NOT NULL DEFAULT 'PENDIENTE',
    url_descarga TEXT,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMPTZ,    
    fecha_expiracion_enlace TIMESTAMPTZ 
);

/*
 * Registra las solicitudes de eliminación de cuenta (RF-POR-DEL-001).
 */
CREATE TABLE solicitudes_eliminacion (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,    
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion_programada TIMESTAMPTZ NOT NULL 
);

-- Módulo de Definición (Gestión de hábitos)

/*
 * Almacena las categorías personalizadas creadas por cada usuario
 * para organizar sus hábitos.
 */
CREATE TABLE categorias (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,    
    color_hex VARCHAR(7) DEFAULT '#CCCCCC', 

    CONSTRAINT uq_categoria_usuario_nombre UNIQUE (usuario_id, UPPER(nombre))
);

/*
 * Almacena la definición de cada hábito creado por un usuario (SRS 4.2).
 */
CREATE TABLE habitos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    meta_diaria NUMERIC(10, 2),
    esta_archivado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ,

    CONSTRAINT chk_habito_nombre_longitud CHECK (LENGTH(nombre) >= 3),
    CONSTRAINT chk_habito_meta_diaria CHECK (meta_diaria IS NULL OR meta_diaria > 0),    
    CONSTRAINT uq_habito_usuario_nombre UNIQUE (usuario_id, UPPER(nombre))
);

/*
 * Tabla pivote para la relación N:M entre hábitos y categorías.
 */
CREATE TABLE habito_categorias (
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    categoria_id BIGINT NOT NULL REFERENCES categorias(id) ON DELETE CASCADE,    
    PRIMARY KEY (habito_id, categoria_id)
);

-- Módulo de Seguimiento (Registros y cumplimientos)

/*
 * Almacena las entradas de cumplimiento diario para cada hábito (SRS 4.3).
 */
CREATE TABLE registros_diarios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    fecha_registro DATE NOT NULL,    
    valor_registrado NUMERIC(10, 2) NOT NULL,
    esta_cumplido BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMPTZ,

    CONSTRAINT uq_registro_habito_fecha UNIQUE (habito_id, fecha_registro),
    CONSTRAINT chk_registro_valor_positivo CHECK (valor_registrado > 0)
);

/*
 * Almacena el historial de cambios de los registros diarios (RF-LOG-EDI-005).
 * Se llena mediante triggers en la BD o lógica en la capa de servicio (Spring).
 */
CREATE TABLE registros_diarios_auditoria (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo_operacion tipo_operacion_auditoria NOT NULL,
    registro_id BIGINT,
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    usuario_modificador_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha_registro_auditada DATE,
    valor_anterior NUMERIC(10, 2),
    esta_cumplido_anterior BOOLEAN,
    valor_nuevo NUMERIC(10, 2),
    esta_cumplido_nuevo BOOLEAN,
    fecha_operacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auditoria_habito_id ON registros_diarios_auditoria(habito_id);
CREATE INDEX idx_registros_diarios_fecha ON registros_diarios(fecha_registro);

-- Módulo de Inteligencia (Análisis y métricas)

/*
 * Almacena métricas calculadas para optimizar el rendimiento de la app (RF-RAC-CAL-002).
 * Se actualiza mediante lógica de la aplicación (Spring) cada vez que un
 * registro diario es modificado.
 */
CREATE TABLE habito_metricas_calculadas (
    habito_id BIGINT PRIMARY KEY REFERENCES habitos(id) ON DELETE CASCADE,
    racha_mas_larga INT NOT NULL DEFAULT 0,
    total_dias_cumplidos INT NOT NULL DEFAULT 0,
    total_valor_acumulado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_ultima_actualizacion TIMESTAMPTZ
);

/*
 * Almacena las metas mensuales definidas por el usuario para un hábito (SRS 4.7).
 */
CREATE TABLE metas_mensuales (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,    
    mes SMALLINT NOT NULL CHECK (mes >= 1 AND mes <= 12),
    anio SMALLINT NOT NULL CHECK (anio >= 2020),
    objetivo_dias_cumplidos SMALLINT CHECK (objetivo_dias_cumplidos IS NULL OR objetivo_dias_cumplidos > 0),    
    objetivo_valor_acumulado NUMERIC(12, 2) CHECK (objetivo_valor_acumulado IS NULL OR objetivo_valor_acumulado > 0),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ,

    CONSTRAINT uq_meta_habito_mes_anio UNIQUE (habito_id, mes, anio),
    CONSTRAINT chk_meta_al_menos_un_objetivo CHECK (objetivo_dias_cumplidos IS NOT NULL OR objetivo_valor_acumulado IS NOT NULL)
);
-- Módulo de Notificaciones (Alertas y recordatorios)

/*
 * Almacena la configuración de un recordatorio para un hábito (SRS 4.8).
 */
CREATE TABLE recordatorios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    hora_recordatorio TIME NOT NULL,
    mensaje TEXT,
    esta_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ,
    
    CONSTRAINT uq_recordatorio_habito_hora UNIQUE (habito_id, hora_recordatorio)
);

/*
 * Tabla pivote para la relación N:M entre recordatorios y los días
 * de la semana en que están activos (RF-REC-CON-001).
 */
CREATE TABLE recordatorio_dias (
    recordatorio_id BIGINT NOT NULL REFERENCES recordatorios(id) ON DELETE CASCADE,
    dia dia_semana NOT NULL,
    
    PRIMARY KEY (recordatorio_id, dia)
);

/*
 * Almacena un historial de todas las notificaciones simuladas
 * que han sido disparadas por el sistema (RF-REC-DIS-003).
 */
CREATE TABLE registros_notificaciones (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recordatorio_id BIGINT NOT NULL REFERENCES recordatorios(id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha_disparo TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(50) NOT NULL DEFAULT 'ENVIADO'
);

CREATE INDEX idx_registros_notificaciones_usuario ON registros_notificaciones(usuario_id);