-- =========
--   ENUMS
-- =========

CREATE TYPE estado_usuario AS ENUM ('PENDIENTE_VERIFICACION', 'ACTIVO', 'BLOQUEADO', 'ELIMINACION_PROGRAMADA');
CREATE TYPE formato_fecha AS ENUM ('DD/MM/AAAA', 'MM/DD/AAAA', 'AAAA-MM-DD');
CREATE TYPE estado_exportacion AS ENUM ('PENDIENTE', 'PROCESANDO', 'COMPLETADA', 'FALLIDA');
CREATE TYPE tipo_operacion_auditoria AS ENUM ('INSERCION', 'MODIFICACION', 'ELIMINACION');
CREATE TYPE dia_semana AS ENUM ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES','SABADO', 'DOMINGO');

-- =================
--      TABLAS
-- =================

-- Módulo de Seguridad (Gestión de cuentas)

/*
 * Almacena los roles del sistema (justificada para Spring Security).
 */
CREATE TABLE roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

/*
 * Almacena todos los usuarios de Kumo (SRS 4.1 y 4.6)
 */
CREATE TABLE usuarios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    nombre VARCHAR(100),
    avatar_url TEXT,
    email VARCHAR(255) NOT NULL UNIQUE,
    clave_hash VARCHAR(255) NOT NULL,
    estado estado_usuario NOT NULL DEFAULT 'PENDIENTE_VERIFICACION',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ
);

CREATE INDEX idx_usuarios_email ON usuarios(email);

/*
 * Tabla pivote para la relación N:M entre usuarios y roles.
 */
CREATE TABLE usuario_roles (
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,

    PRIMARY KEY (usuario_id, rol_id)
);

/*
 * Almacena las preferencias de visualización del usuario (RF-PER-PREF-001, RF-PER-PREF-002)
 * Es una relación 1:1 con la tabla 'usuarios' para cumplir SRP.
 */
CREATE TABLE preferencias_usuario (
    usuario_id BIGINT PRIMARY KEY REFERENCES usuarios(id) ON DELETE CASCADE,    
    zona_horaria VARCHAR(100) NOT NULL DEFAULT 'America/Lima',
    formato_fecha formato_fecha NOT NULL DEFAULT 'DD/MM/AAAA'
);

/*
 * Registra los intentos de inicio de sesión fallidos (RF-AUT-INI-003).
 */
CREATE TABLE intentos_login (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    email VARCHAR(255) NOT NULL,
    ip_direccion VARCHAR(50),
    fecha_intento TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_intentos_login_email ON intentos_login(email);

/*
 * Almacena los tokens para restablecer contraseña (RF-AUT-PAS-001).
 */
CREATE TABLE tokens_recuperacion_clave (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,    
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    utilizado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_tokens_recuperacion_hash ON tokens_recuperacion_clave(token_hash);

/*
 * Registra las solicitudes de exportación de datos (RF-POR-EXP-001).
 */
CREATE TABLE solicitudes_exportacion (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,    
    estado estado_exportacion NOT NULL DEFAULT 'PENDIENTE',
    url_descarga TEXT,
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMPTZ,    
    fecha_expiracion_enlace TIMESTAMPTZ 
);

/*
 * Registra las solicitudes de eliminación de cuenta (RF-POR-DEL-001).
 */
CREATE TABLE solicitudes_eliminacion (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,    
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ejecucion_programada TIMESTAMPTZ NOT NULL 
);