-- Módulo de Definición (Gestión de hábitos)

/*
 * Almacena las categorías personalizadas creadas por cada usuario
 * para organizar sus hábitos.
 */
CREATE TABLE categorias (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,    
    color_hex VARCHAR(7) DEFAULT '#CCCCCC'
);

CREATE UNIQUE INDEX idx_categoria_usuario_nombre_unico ON categorias (usuario_id, UPPER(nombre));

/*
 * Almacena la definición de cada hábito creado por un usuario (SRS 4.2).
 */
CREATE TABLE habitos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    meta_diaria NUMERIC(10, 2),
    esta_archivado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ,

    CONSTRAINT chk_habito_nombre_longitud CHECK (LENGTH(nombre) >= 3),
    CONSTRAINT chk_habito_meta_diaria CHECK (meta_diaria IS NULL OR meta_diaria > 0)
);

CREATE UNIQUE INDEX idx_habito_usuario_nombre_unico ON habitos (usuario_id, UPPER(nombre));
CREATE INDEX idx_habitos_usuario_id ON habitos(usuario_id);

/*
 * Tabla pivote para la relación N:M entre hábitos y categorías.
 */
CREATE TABLE habito_categorias (
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    categoria_id BIGINT NOT NULL REFERENCES categorias(id) ON DELETE CASCADE,    
    PRIMARY KEY (habito_id, categoria_id)
);
