-- Módulo de Seguimiento (Registros y cumplimientos)

/*
 * Almacena las entradas de cumplimiento diario para cada hábito (SRS 4.3).
 */
CREATE TABLE registros_diarios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    fecha_registro DATE NOT NULL,    
    valor_registrado NUMERIC(10, 2) NOT NULL,
    esta_cumplido BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_modificacion TIMESTAMPTZ,

    CONSTRAINT uq_registro_habito_fecha UNIQUE (habito_id, fecha_registro),
    CONSTRAINT chk_registro_valor_positivo CHECK (valor_registrado > 0)
);

/*
 * Almacena el historial de cambios de los registros diarios (RF-LOG-EDI-005).
 * Se llena mediante triggers en la BD o lógica en la capa de servicio (Spring).
 */
CREATE TABLE registros_diarios_auditoria (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tipo_operacion tipo_operacion_auditoria NOT NULL,
    registro_id BIGINT,
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    usuario_modificador_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha_registro_auditada DATE,
    valor_anterior NUMERIC(10, 2),
    esta_cumplido_anterior BOOLEAN,
    valor_nuevo NUMERIC(10, 2),
    esta_cumplido_nuevo BOOLEAN,
    fecha_operacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auditoria_habito_id ON registros_diarios_auditoria(habito_id);
CREATE INDEX idx_registros_diarios_fecha ON registros_diarios(fecha_registro);
