-- Módulo de Inteligencia (Análisis y métricas)

/*
 * Almacena métricas calculadas para optimizar el rendimiento de la app (RF-RAC-CAL-002).
 * Se actualiza mediante lógica de la aplicación (Spring) cada vez que un
 * registro diario es modificado.
 */
CREATE TABLE habito_metricas_calculadas (
    habito_id BIGINT PRIMARY KEY REFERENCES habitos(id) ON DELETE CASCADE,
    version BIGINT NOT NULL DEFAULT 0,
    racha_mas_larga INT NOT NULL DEFAULT 0,
    total_dias_cumplidos INT NOT NULL DEFAULT 0,
    total_valor_acumulado NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_ultima_actualizacion TIMESTAMPTZ
);

/*
 * Almacena las metas mensuales definidas por el usuario para un hábito (SRS 4.7).
 */
CREATE TABLE metas_mensuales (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,    
    mes SMALLINT NOT NULL CHECK (mes >= 1 AND mes <= 12),
    anio SMALLINT NOT NULL CHECK (anio >= 2020),
    objetivo_dias_cumplidos SMALLINT CHECK (objetivo_dias_cumplidos IS NULL OR objetivo_dias_cumplidos > 0),    
    objetivo_valor_acumulado NUMERIC(12, 2) CHECK (objetivo_valor_acumulado IS NULL OR objetivo_valor_acumulado > 0),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ,

    CONSTRAINT uq_meta_habito_mes_anio UNIQUE (habito_id, mes, anio),
    CONSTRAINT chk_meta_al_menos_un_objetivo CHECK (objetivo_dias_cumplidos IS NOT NULL OR objetivo_valor_acumulado IS NOT NULL)
);