-- Módulo de Notificaciones (Alertas y recordatorios)

/*
 * Almacena la configuración de un recordatorio para un hábito (SRS 4.8).
 */
CREATE TABLE recordatorios (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    habito_id BIGINT NOT NULL REFERENCES habitos(id) ON DELETE CASCADE,
    hora_recordatorio TIME NOT NULL,
    mensaje TEXT,
    esta_activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMPTZ,
    
    CONSTRAINT uq_recordatorio_habito_hora UNIQUE (habito_id, hora_recordatorio)
);

/*
 * Tabla pivote para la relación N:M entre recordatorios y los días
 * de la semana en que están activos (RF-REC-CON-001).
 */
CREATE TABLE recordatorio_dias (
    recordatorio_id BIGINT NOT NULL REFERENCES recordatorios(id) ON DELETE CASCADE,
    dia dia_semana NOT NULL,
    
    PRIMARY KEY (recordatorio_id, dia)
);

/*
 * Almacena un historial de todas las notificaciones simuladas
 * que han sido disparadas por el sistema (RF-REC-DIS-003).
 */
CREATE TABLE registros_notificaciones (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recordatorio_id BIGINT NOT NULL REFERENCES recordatorios(id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha_disparo TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(50) NOT NULL DEFAULT 'ENVIADO'
);

CREATE INDEX idx_registros_notificaciones_usuario ON registros_notificaciones(usuario_id);
CREATE INDEX idx_recordatorios_habito_id ON recordatorios(habito_id);